# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scottish Enterprise September MVS
email: graeme.laurenson@scotent.co.uk

description: > # this means to ignore newlines until "baseurl:"

repository: "scotent/sept-mvs"
url: "https://scotent.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/sept-mvs"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
