preferred_syntax = :sass
http_path = '/'
css_dir = 'css'
sass_dir = '_sass'
images_dir = 'images'
javascripts_dir = 'javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed